# Generated by Django 3.2.8 on 2021-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(help_text='Enter title (60 characters max), on_delete=models.CASCADE, null=True, blank=True', max_length=60),
        ),
    ]
