# Generated by Django 3.2.8 on 2021-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, help_text='Enter title (60 characters max)', max_length=60, null=True),
        ),
    ]
