# Generated by Django 3.2.8 on 2021-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(help_text='Write your post...', max_length=400),
        ),
    ]
